# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='notes',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='strong_reason',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='weak_reason',
            field=models.TextField(max_length=500),
        ),
    ]
