# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(max_length=500)),
                ('author', models.CharField(max_length=25)),
                ('notes', models.TextField()),
            ],
        ),
    ]
