# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyforecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(max_length=500)),
                ('strong_cur', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('NZD', 'NZD')], default='USD', max_length=3)),
                ('strong_reason', models.CharField(max_length=500)),
                ('weak_cur', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('NZD', 'NZD')], default='USD', max_length=3)),
                ('weak_reason', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
