# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20170525_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=500)),
                ('currency', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('time_eastern', models.CharField(max_length=50)),
                ('forecast', models.CharField(max_length=50)),
                ('previous', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
