# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_auto_20170525_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='strong_cur',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('NZD', 'NZD'), ('---', '---')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='strong_reason',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='weak_cur',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('NZD', 'NZD'), ('---', '---')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='weak_reason',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
